import Head from "next/head";
import { HomeIndex, Nav } from "@/components";
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie App - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        strategy="beforeInteractive"
        src="https://kit.fontawesome.com/336b0701e1.js"
      ></Script>
      <Nav />
      <HomeIndex />
    </>
  );
}
